# Generated by Django 2.2.19 on 2023-03-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230227_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AmoutIngredient',
            new_name='AmountIngredient',
        ),
    ]
