# Generated by Django 4.1.7 on 2023-03-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_amountingredient_id_alter_ingredients_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='is_favorite',
            new_name='in_favorites',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
